# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_v8-2Yq6fWVoG173om8odueCAdihGSO
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib, cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mping
# %matplotlib inline

img = cv2.imread('/content/sample_data/kucing3.jpeg')
img = mping.imread('/content/sample_data/kucing3.jpeg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(gray_image)

plt.imshow(cv2.cvtColor(gray_image, cv2.COLOR_BGR2RGB))

from PIL import Image
import numpy as np

im = np.array(Image.open('/content/sample_data/kucing3.jpeg'))
plt.imshow(im, cmap='gray')

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('/content/sample_data/kucing3.jpeg')
#image rotate
h,w = img.shape[:2]
center = (w/2, h/2)
angle = 35
scale = 1
m = cv2.getRotationMatrix2D(center, angle, scale)
rotated = cv2.warpAffine(img, m, (w,h))
img_rotate = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

#image crop
img_crop = img[50:150, 50:150]
img_flip = cv2.flip(img, 1) # Flip horizontally

fig,ax = plt.subplots(2,2 ,figsize=(10,10))
ax[0,0].imshow(img_flip)
ax[0,0].set_title('image flip')
ax[0,1].imshow(img_rotate)
ax[0,1].set_title('image rotate')
ax[1,0].imshow(img) # Display original image or another transformation
ax[1,0].set_title('Original image')
ax[1,1].imshow(img_crop)
ax[1,1].set_title('image crop')

plt.tight_layout()
plt.show()

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

#open data
img_cv = cv2.imread('/content/sample_data/kucing3.jpeg')#open data mpimg
img_plt = mpimg.imread('/content/sample_data/kucing3.jpeg')

fig, ax = plt.subplots(1,2, figsize=(10,10))
ax[0].imshow(img_cv)
ax[0].set_title('Open CV')
ax[1].imshow(img_plt)
ax[1].set_title('Matplotlib')


plt.show()

#imgcv
imgcv = img_cv.copy()
#imgcv RGB
imgcv_rgb = cv2.cvtColor(imgcv, cv2.COLOR_BGR2RGB)

#image HSV (hue, saturation, value)
imgcv_hsv = cv2.cvtColor(imgcv, cv2.COLOR_BGR2HSV)

#image gray
imgcv_gray = cv2.cvtColor(imgcv, cv2.COLOR_BGR2GRAY)

#image binary
_, binary = cv2.threshold(imgcv_gray, 128, 255, cv2.THRESH_BINARY)


fig, ax = plt.subplots(2, 2, figsize=(10, 10)) # Change to 2x2 grid

ax[0,0].imshow(imgcv_rgb) # Display RGB in the first subplot
ax[0,0].set_title('RGB')

ax[0,1].imshow(imgcv_hsv) # Display HSV in the second subplot
ax[0,1].set_title('HSV')

ax[1,0].imshow(imgcv_gray, cmap='gray') # Display Gray in the third subplot (use cmap='gray' for grayscale)
ax[1,0].set_title('Gray')

ax[1,1].imshow(binary, cmap='gray') # Display Binary in the fourth subplot
ax[1,1].set_title('Binary')

# Hide axes for cleaner look
for row in ax:
    for col in row:
        col.axis('off')

plt.tight_layout()
plt.show()

import cv2
import matplotlib.pyplot as plt

# Load the image using cv2.imread
img = cv2.imread('/content/pexels-pixabay-163822.jpg')

# Convert the image from BGR to RGB for displaying with Matplotlib
imgcv_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Split the RGB image into its channels
b, g, r= cv2.split(imgcv_rgb)

fig, ax = plt.subplots(2, 2, figsize=(10, 10))

# Display Red channel
ax[0,0].imshow(r, cmap='red')
ax[0,0].set_title('R Channel')
ax[0,0].axis('off')

# Display Green channel
ax[0,1].imshow(g, cmap='green')
ax[0,1].set_title('G Channel')
ax[0,1].axis('off')

# Display Blue channel
ax[1,0].imshow(b, cmap='blue')
ax[1,0].set_title('B Channel')
ax[1,0].axis('off')

# Display original RGB image for comparison
ax[1,1].imshow(imgcv_rgb)
ax[1,1].set_title('Original RGB')
ax[1,1].axis('off')


plt.tight_layout()
plt.show()

#imgcv
imgcv = cv2.imread('/content/pexels-pixabay-163822.jpg')
#imgcv RGB
imgcv_rgb = cv2.cvtColor(imgcv, cv2.COLOR_BGR2RGB)

#image HSV (hue, saturation, value)
imgcv_hsv = cv2.cvtColor(imgcv, cv2.COLOR_BGR2HSV)

#image gray
# imgcv_gray = cv2.cvtColor(imgcv, cv2.COLOR_BGR2GRAY)

#image binary
_, binary = cv2.threshold(imgcv_gray, 128, 255, cv2.THRESH_BINARY)

# Split RGB channels
r, g, b = cv2.split(imgcv_rgb)

# Add value to Red channel
r_add = cv2.add(r, 100)


# fig1, ax1 = plt.subplots(2, 2, figsize=(10, 10)) # Create a 2x2 grid for color spaces

#ax1[0,0].imshow(imgcv_rgb)
#ax1[0,0].set_title('RGB')
#ax1[0,0].axis('off')

#ax1[0,1].imshow(imgcv_hsv)
#ax1[0,1].set_title('HSV')
#ax1[0,1].axis('off')

#ax1[1,0].imshow(imgcv_gray, cmap='gray')
#ax1[1,0].set_title('Gray')
#ax1[1,0].axis('off')

#ax1[1,1].imshow(binary, cmap='gray')
#ax1[1,1].set_title('Binary')
#ax1[1,1].axis('off')


fig2, ax2 = plt.subplots(1, 3, figsize=(15, 5)) # Create a 1x3 grid for RGB channels

ax2[0].imshow(r, cmap='Reds')
ax2[0].set_title('R Channel')
ax2[0].axis('off')

ax2[1].imshow(g, cmap='Greens')
ax2[1].set_title('G Channel')
ax2[1].axis('off')

ax2[2].imshow(b, cmap='Blues')
ax2[2].set_title('B Channel')
ax2[2].axis('off')


# gray_r = cv2.cvtColor(r, cv2.COLOR_GRAY2RGB)
# gray_g = cv2.cvtColor(g, cv2.COLOR_GRAY2RGB)
# gray_b = cv2.cvtColor(b, cv2.COLOR_GRAY2RGB)

# fig,ax = plt.subplots(2,2, figsize=(10,10))
# ax[0,0].imshow(gray_r, cmap='Reds')
# ax[0,0].set_title('image R gray')
# ax[0,1].imshow(gray_g, cmap='Greens')
# ax[0,1].set_title('image G gray')
# ax[1,0].imshow(gray_b, cmap='Blues')
# ax[1,0].set_title('image B gray')


fig3, ax3 = plt.subplots(1, 1, figsize=(5, 5)) # Create a single plot for the modified Red channel
ax3.imshow(r_add, cmap='Reds')
ax3.set_title('R Channel with added value')
ax3.axis('off')

img_r_add_merge = cv2.merge((r_add, g, b))
plt.imshow(img_r_add_merge)

plt.tight_layout()
plt.show()

from PIL import Image
import numpy as np


im = np.array(Image.open('/content/pexels-pixabay-163822.jpg'))

im_R = im.copy()
im_R[:,:,(1,2)] = 0  # Set Green and Blue channels to 0 for Red channel display
im_G = im.copy()
im_G[:,:,(0,2)] = 0  # Set Red and Blue channels to 0 for Green channel display
im_B = im.copy()
im_B[:,:,(0,1)] = 0  # Set Red and Green channels to 0 for Blue channel display


fig, ax = plt.subplots(2,2, figsize=(10,10))

# Display Red channel
ax[0,0].imshow(im_R)
ax[0,0].set_title('R Channel')
ax[0,0].axis('off')

# Display Green channel
ax[0,1].imshow(im_G)
ax[0,1].set_title('G Channel')
ax[0,1].axis('off')

# Display Blue channel
ax[1,0].imshow(im_B)
ax[1,0].set_title('B Channel')
ax[1,0].axis('off')

# Display original image
ax[1,1].imshow(im)
ax[1,1].set_title('Original Image')
ax[1,1].axis('off')


print(im_G)
plt.tight_layout()
plt.show()

img_small = cv2.resize(img, (100, 100))
img_large = cv2.resize(img, (500, 500))

print('resolusi asli', imgcv_rgb.shape)
print('resolusi kecil', img_small.shape)
print('resolusi besar', img_large.shape)

ax[0]

#NOISE
noise = np.random.normal(0, 25, imgcv_rgb.shape).astype(np.uint8)
noise_img = cv2.add(imgcv_rgb, noise)

blur_img = cv2.blur(noise_img, (5, 5), 0)
gaussian = cv2.GaussianBlur(imgcv_rgb, (5, 5), 0)

fig, ax = plt.subplots(2, 2, figsize=(10, 10))
ax[0].imshow(imgcv_rgb)
ax[0].set_title('Original Image')
ax[0].axis('off')

ax[1].imshow(noise_img)
ax[1].set_title('Noisy Image')
ax[1].axis('off')

ax[2].imshow(blur_img)
ax[2].set_title('Blurred Image')
ax[2].axis('off')

plt.tight_layout()
plt.show()

import os
cv2.imwrite('/content/pexels-pixabay-163822_90.jpg', cv2.cvtColor(imgcv_rgb, cv2.COLOR_RGB2BGR), [cv2.IMWRITE_JPEG_QUALITY, 100])
cv2.imwrite('/content/pexels-pixabay-163822_60.jpg', cv2.cvtColor(imgcv_rgb, cv2.COLOR_RGB2BGR), [cv2.IMWRITE_JPEG_QUALITY, 60])
cv2.imwrite('/content/pexels-pixabay-163822_30.jpg', cv2.cvtColor(imgcv_rgb, cv2.COLOR_RGB2BGR), [cv2.IMWRITE_JPEG_QUALITY, 30])

img90 = cv2.cvtColor(cv2.imread('/content/pexels-pixabay-163822_90.jpg'), cv2.COLOR_BGR2RGB)
img60 = cv2.cvtColor(cv2.imread('/content/pexels-pixabay-163822_60.jpg'), cv2.COLOR_BGR2RGB)
img30 = cv2.cvtColor(cv2.imread('/content/pexels-pixabay-163822_30.jpg'), cv2.COLOR_BGR2RGB)

fig, ax = plt.subplots(1, 3, figsize=(10, 10))
ax[0].imshow(img90)
ax[0].set_title('90')
ax[1].imshow(img60)
ax[1].set_title('60')
ax[2].imshow(img30)
ax[2].set_title('30')

print(os.path.getsize('/content/pexels-pixabay-163822_90.jpg'))
print(os.path.getsize('/content/pexels-pixabay-163822_60.jpg'))
print(os.path.getsize('/content/pexels-pixabay-163822_30.jpg'))





plt.tight_layout()
plt.show()

#menghitung tingkat error dari citra

from skimage.metrics import mean_squared_error

mse90 = mean_squared_error(imgcv_rgb, img90)
mse60 = mean_squared_error(imgcv_rgb, img60)
mse30 = mean_squared_error(imgcv_rgb, img30)

print('mse90', mse90)
print('mse60', mse60)
print('mse30', mse30)