# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_v8-2Yq6fWVoG173om8odueCAdihGSO
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib, cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mping
# %matplotlib inline

img = cv2.imread('/content/sample_data/kucing3.jpeg')
img = mping.imread('/content/sample_data/kucing3.jpeg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(gray_image)

plt.imshow(cv2.cvtColor(gray_image, cv2.COLOR_BGR2RGB))

from PIL import Image
import numpy as np

im = np.array(Image.open('/content/sample_data/kucing3.jpeg'))
plt.imshow(im, cmap='gray')

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('/content/sample_data/kucing3.jpeg')
#image rotate
h,w = img.shape[:2]
center = (w/2, h/2)
angle = 35
scale = 1
m = cv2.getRotationMatrix2D(center, angle, scale)
rotated = cv2.warpAffine(img, m, (w,h))
img_rotate = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

#image crop
img_crop = img[50:150, 50:150]
img_flip = cv2.flip(img, 1) # Flip horizontally

fig,ax = plt.subplots(2,2 ,figsize=(10,10))
ax[0,0].imshow(img_flip)
ax[0,0].set_title('image flip')
ax[0,1].imshow(img_rotate)
ax[0,1].set_title('image rotate')
ax[1,0].imshow(img) # Display original image or another transformation
ax[1,0].set_title('Original image')
ax[1,1].imshow(img_crop)
ax[1,1].set_title('image crop')

plt.tight_layout()
plt.show()

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

#open data
img_cv = cv2.imread('/content/sample_data/kucing3.jpeg')
#open data mpimg
img_plt = mpimg.imread('/content/sample_data/kucing3.jpeg')

fig, ax = plt.subplots(1,2, figsize=(10,10))
ax[0].imshow(img_cv)
ax[0].set_title('Open CV')
ax[1].imshow(img_plt)
ax[1].set_title('Matplotlib')


plt.show()

imgcv = img_cv.copy()

imgcv_rgb = cv2.cvtColor(imgcv, cv2.COLOR_BGR2RGB)

fig, ax = plt.subplots(1,2, figsize=(8,16))
ax[0].imshow(imgcv)
ax[0].set_title('Open CV')
ax[1].imshow(imgcv_rgb)
ax[1].set_title('RGB')

plt.show()
plt.imshow(imgcv_rgb)